defaultEntryPoints = ["http", "https"]
debug = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[web]
address = ":8080"

[acme]
email = "jlevesy@gmail.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"

[acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
   main = "julienlevesy.net"
   sans = ["me.julienlevesy.net", "stack.julienlevesy.net"]

[docker]
watch = true
