defaultEntryPoints = ["http", "https"]
debug = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]

email = "jlevesy@gmail.com"
storage = "/etc/traefik/acme.json"
entryPoint = "https"

[[acme.domains]]
   main = "julienlevesy.net"
   sans = ["me.julienlevesy.net"]

[docker]
watch = true
