---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    machine_hostname: "{{ lookup('env', 'MACHINE_HOSTNAME') }}"
    root_password: "{{ lookup('env', 'MACHINE_ROOT_PASSWORD') }}"
    primary_user: "{{ lookup('env', 'MACHINE_PRIMARY_USER') }}"
    primary_password: "{{ lookup('env', 'MACHINE_PRIMARY_PASSWORD') }}"
    primary_public_keys:
      - "{{ lookup('env', 'MACHINE_PRIMARY_PUBLIC_KEY') }}"

    docker_ca_key_passphrase: "{{ lookup('env','DOCKER_CA_KEY_PASSPHRASE') }}"
    domain: "{{ lookup('env', 'DOMAIN') }}"

    docker_client_tls_path: "{{ lookup('env', 'DOCKER_CLIENT_TLS_PATH') }}"

    sshd_port: 22
    tcp_open_ports:
      - 80
      - 443
      - 8080
      - 2376
  roles:
    - common
    - docker
    - docker-tls
