# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/stretch64'

  config.vm.network :forwarded_port, guest: 2376, host: 23_376
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'main.yml'
    # ansible.verbose = 'vvv'
  end
end
