version: '3'

networks:
  web:
    driver: bridge
  grafana_sources:
    driver: bridge

services:
  lb:
    image: ${REGISTRY}/traefik
    ports:
      - 80:80
      - 443:443
    command: [
      "--docker",
      "--docker.watch",
      "--web",
      "--web.metrics.prometheus",
      "--configFile=/etc/traefik/traefik.toml"
    ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

  grafana:
    image: grafana/grafana
    volumes:
      - /var/lib/grafana:/data/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://metrics.${DOMAIN}
    labels:
      - "traefik.port=3000"
      - "traefik.backend=metrics"
      - "traefik.frontend.rule=Host:metrics.${DOMAIN}"
      - "traefik.docker.network=admin_web"
    networks:
      - web
      - grafana_sources
