version: '3'

networks:
  web:
    driver: bridge

services:
  lb:
    image: ${REGISTRY}/traefik
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: [
      "--docker",
      "--docker.swarmmode",
      "--docker.domain=${DOMAIN}",
      "--docker.watch",
      "--web",
      "--configFile=/etc/traefik/traefik.toml"
    ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
