---

- name: install python necessary packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pip

- name: install docker-compose
  pip:
    name: docker-compose
