defaultEntryPoints = ["http", "https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "tests/traefik.crt"
      keyFile = "tests/traefik.key"
[acme]
email = "jlevesy@gmail.io"
storageFile = "acme.json"
entryPoint = "https"
[[acme.domains]]
   main = "julienlevesy.net"
   sans = ["me.julienlevesy.net", "talks.julienlevesy.net", "grafana.julienlevesy.net"]
