defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]

email = "jlevesy@gmail.com"
storage = "acme.json"
entryPoint = "https"

[[acme.domains]]
   main = "julienlevesy.net"
   sans = ["me.julienlevesy.net", "talks.julienlevesy.net", "metrics.julienlevesy.net", "git.julienlevesy.net"]
