---

- name: update packages listing
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: upgrade the system
  apt:
    upgrade: dist

- name: install common packages
  apt:
    state: installed
    pkg: "{{ item }}"
  with_items: "{{ common_packages }}"

- name: setup automatic updates interval
  copy:
    src: apt_periodic
    dest: /etc/apt/apt.conf.d/02periodic

- name: set hostname
  hostname:
    name: "{{ machine_hostname }}"

- name: "update hosts file"
  lineinfile:
    dest: /etc/hosts
    line: "::1  {{ machine_hostname }}"
    state: present

- name: change root password
  user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"

- name: add primary user
  user:
    name: "{{ primary_user }}"
    password: "{{ primary_password | password_hash('sha512') }}"
    groups: 'sudo'
    shell: '/bin/bash'

- name: add authorized keys for {{primary_user}}
  authorized_key:
    user: "{{ primary_user }}"
    key: "{{ lookup('file', item) }}"
  with_items: "{{ primary_public_keys }}"

- name: setup ufw
  ufw:
    state: enabled
    policy: deny

- set_fact:
    sshd_port_as_list:
      - "{{ sshd_port }}"

- name: allow TCP trafic on ports required ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ tcp_open_ports + sshd_port_as_list }}"

- name: harden sshd configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
    state: present
  with_items:
    - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication no" }
    - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin no" }
    - { regexp: "^#?X11Forwarding", line: "X11Forwarding no" }
    - { regexp: "^#?AllowTcpForwarding", line: "AllowTcpForwarding yes" }
    - { regexp: "^#?Port", line: "Port {{ sshd_port }}" }
  notify: restart ssh
