version: '3'

networks:
  web:
    driver: bridge

services:
  lb:
    image: traefik
    ports:
      - 8080:8080
      - 80:80
      - 443:443
    command: [
      "--docker",
      "--docker.watch",
      "--web",
      "--web.metrics.prometheus",
      "--debug"
    ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
  home:
    image: jlevesy/home
    networks:
      - web
    labels:
      - "traefik.port=80"
      - "traefik.backend=home"
      - "traefik.frontend.rule=Host:${DOMAIN}"
      - "traefik.docker.network=web"
  resume:
    image: jlevesy/resume
    networks:
      - web
    labels:
      - "traefik.port=80"
      - "traefik.backend=home"
      - "traefik.frontend.rule=Host:me.${DOMAIN}"
      - "traefik.docker.network=web"
  talks:
    image: jlevesy/talks
    networks:
      - web
    labels:
      - "traefik.port=80"
      - "traefik.backend=home"
      - "traefik.frontend.rule=Host:talks.${DOMAIN}"
      - "traefik.docker.network=web"
