version: '3'

networks:
  web:
    external:
      name: "admin_web"

services:
  home:
    image: ${REGISTRY}/home
    networks:
      - web
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.backend=home"
        - "traefik.frontend.rule=Host:${DOMAIN}"
        - "traefik.docker.network=admin_web"
  resume:
    image: ${REGISTRY}/resume
    networks:
      - web
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.backend=resume"
        - "traefik.frontend.rule=Host:me.${DOMAIN}"
        - "traefik.docker.network=admin_web"
  talks:
    image: ${REGISTRY}/talks
    networks:
      - web
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.backend=talks"
        - "traefik.frontend.rule=Host:talks.${DOMAIN}"
        - "traefik.docker.network=admin_web"
